# Introduction to TensorFlow in Python

## Chapter 1

In [28]:
import io
from google.colab import drive
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow import constant, Variable, float32
from tensorflow import multiply, ones_like, matmul, reduce_sum, reshape

import matplotlib.pyplot as plt

In [25]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [15]:
# Assign the path to a string variable named data_path
data_path = "/content/drive/My Drive/datasets/datacamp/uci_credit_card.csv"

credit_df = pd.read_csv(data_path)
credit_df

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1   24      2      2     -1   
1          2   120000.0    2          2         2   26     -1      2      0   
2          3    90000.0    2          2         2   34      0      0      0   
3          4    50000.0    2          2         1   37      0      0      0   
4          5    50000.0    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996   220000.0    1          3         1   39      0      0      0   
29996  29997   150000.0    1          3         2   43     -1     -1     -1   
29997  29998    30000.0    1          2         2   37      4      3      2   
29998  29999    80000.0    1          3         1   41      1     -1      0   
29999  30000    50000.0    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...        0.0        0.0        0.0       0.0     689.0   
1          0  ...     3272.0     3455.0     3261.0       0.0    1000.0   
2          0  ...    14331.0    14948.0    15549.0    1518.0    1500.0   
3          0  ...    28314.0    28959.0    29547.0    2000.0    2019.0   
4          0  ...    20940.0    19146.0    19131.0    2000.0   36681.0   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...    88004.0    31237.0    15980.0    8500.0   20000.0   
29996     -1  ...     8979.0     5190.0        0.0    1837.0    3526.0   
29997     -1  ...    20878.0    20582.0    19357.0       0.0       0.0   
29998      0  ...    52774.0    11855.0    48944.0   85900.0    3409.0   
29999      0  ...    36535.0    32428.0    15313.0    2078.0    1800.0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0           0.0       0.0       0.0       0.0                           1  
1        1000.0    1000.0       0.0    2000.0                           1  
2        1000.0    1000.0    1000.0    5000.0                           0  
3        1200.0    1100.0    1069.0    1000.0                           0  
4       10000.0    9000.0     689.0     679.0                           0  
...         ...       ...       ...       ...                         ...  
29995    5003.0    3047.0    5000.0    1000.0                           0  
29996    8998.0     129.0       0.0       0.0                           0  
29997   22000.0    4200.0    2000.0    3100.0                           1  
29998    1178.0    1926.0   52964.0    1804.0                           1  
29999    1430.0    1000.0    1000.0    1000.0                           1  

[30000 rows x 25 columns]

In [16]:
credit_numpy = credit_df[["EDUCATION", "MARRIAGE", "AGE", "BILL_AMT1"]].to_numpy()

In [17]:
# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('\n The datatype is:', credit_constant.dtype)

# Print constant shape
print('\n The shape is:', credit_constant.shape)


 The datatype is: <dtype: 'float64'>

 The shape is: (30000, 4)


In [18]:
# Define the 1-dimensional variable A1
A1 = Variable([1, 2, 3, 4])

# Print the variable A1
print('\n A1: ', A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print('\n B1: ', B1)


 A1:  <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

 B1:  [1 2 3 4]


In [19]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))


 C1: [1 2 3 4]

 C23: [[1 2 3]
 [1 6 4]]


In [22]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


In [26]:
wealth = constant(
    [[11, 50],
     [ 7,  2],
     [ 4, 60],
     [ 3,  0],
     [25, 10]]
  )

print(reduce_sum(wealth))
print(reduce_sum(wealth, 0))
print(reduce_sum(wealth, 1))


tf.Tensor(172, shape=(), dtype=int32)
tf.Tensor([ 50 122], shape=(2,), dtype=int32)
tf.Tensor([61  9 64  3 35], shape=(5,), dtype=int32)


In [27]:
gray_tensor = constant(
    [[187, 189, 190, 192, 195, 198, 198, 198, 200, 200, 201, 205, 206,
        203, 206, 206, 206, 207, 209, 207, 205, 205, 208, 208, 206, 207,
        206, 206],
       [189, 191, 193, 195, 197, 199, 200, 199, 200, 201, 202, 206, 206,
        208, 204, 204, 210, 209, 208, 208, 207, 206, 208, 208, 207, 207,
        207, 207],
       [189, 192, 195, 198, 198, 201, 202, 203, 205, 206, 205, 209, 207,
        204, 211, 210, 205, 208, 211, 208, 206, 207, 209, 210, 210, 208,
        210, 210],
       [191, 192, 195, 197, 199, 199, 204, 201, 203, 208, 206, 207, 209,
        207, 213, 208, 209, 211, 221, 205, 204, 239, 182, 212, 213, 212,
        209, 209],
       [193, 195, 195, 199, 201, 201, 203, 205, 206, 216, 223, 203, 207,
        239, 225, 193, 188, 230, 232, 195, 176, 239, 191, 205, 215, 212,
        211, 213],
       [194, 196, 199, 200, 206, 202, 205, 207, 196, 255, 238, 197, 160,
        235, 226, 191, 146, 190, 226, 201, 160, 228, 211, 162, 215, 214,
        216, 213],
       [195, 198, 201, 202, 202, 203, 232, 215, 197, 246, 230, 215, 153,
        235, 221, 205, 162, 181, 224, 210, 166, 202, 209, 163, 190, 213,
        211, 213],
       [196, 198, 201, 208, 202, 243, 240, 215, 166, 246, 233, 223, 171,
        235, 212, 214, 165, 206, 224, 199, 152, 126, 206, 199, 170, 165,
        214, 215],
       [198, 201, 197, 204, 189, 247, 244, 230, 206, 246, 235, 220, 188,
        235, 211, 218, 142, 227, 223, 176, 152,  74, 192, 206, 200, 145,
        177, 215],
       [200, 203, 206, 206, 236, 254, 254, 233, 215, 205, 242, 219, 185,
        234, 230, 223, 131, 201, 209, 156, 141,  83, 175, 220, 196, 157,
        185, 222],
       [201, 200, 201, 193, 253, 231, 245, 246, 209, 159, 241, 214, 176,
        219, 234, 212, 133, 132, 175, 149, 109, 100, 225, 226, 209, 147,
        219, 221],
       [202, 203, 203, 196, 253, 209, 241, 233, 194, 150, 234, 204, 174,
        160, 208, 189, 146, 101, 172, 145,  76, 195, 230, 226, 194, 121,
        227, 224],
       [204, 203, 210, 245, 251, 222, 207, 198, 152, 112, 207, 171, 163,
         97, 163, 154, 122, 105, 175, 169, 175, 227, 226, 206, 154, 147,
        219, 225],
       [204, 205, 201, 250, 246, 217, 167, 204, 146, 116, 192, 170, 161,
         78, 151, 165, 115, 181, 228, 225, 223, 215, 203, 181, 144, 202,
        220, 227],
       [205, 207, 198, 252, 254, 228, 198, 185, 162, 128, 202, 194, 144,
         64, 135, 155, 237, 241, 237, 226, 211, 177, 179, 155, 142, 227,
        227, 228],
       [210, 211, 208, 255, 252, 240, 219, 187, 168, 148, 187, 202, 151,
        103, 192, 246, 253, 244, 233, 221, 199, 179, 157, 154, 116, 234,
        228, 231],
       [208, 211, 209, 254, 254, 248, 231, 216, 193, 175, 178, 201, 208,
        240, 253, 254, 249, 238, 222, 206, 185, 160, 143, 143, 214, 231,
        230, 230],
       [209, 212, 205, 254, 254, 252, 241, 229, 217, 187, 207, 224, 249,
        253, 251, 250, 242, 228, 206, 183, 166, 150, 143, 172, 229, 234,
        235, 230],
       [208, 211, 206, 254, 254, 255, 249, 238, 231, 211, 213, 230, 250,
        254, 252, 246, 233, 217, 188, 164, 150, 143, 120, 235, 231, 230,
        231, 231],
       [209, 213, 211, 253, 255, 255, 252, 244, 233, 222, 217, 224, 246,
        251, 242, 234, 225, 195, 173, 153, 134, 116, 225, 232, 235, 232,
        233, 233],
       [209, 214, 214, 246, 254, 253, 252, 240, 224, 214, 213, 217, 233,
        233, 230, 214, 199, 190, 150, 145, 127, 201, 233, 234, 232, 234,
        233, 234],
       [211, 215, 215, 243, 254, 254, 245, 232, 221, 208, 213, 218, 225,
        223, 206, 195, 169, 157, 132, 126, 170, 238, 234, 235, 234, 234,
        234, 234],
       [214, 216, 217, 209, 254, 250, 236, 229, 212, 197, 206, 210, 221,
        210, 196, 170, 148, 140, 118, 134, 240, 235, 234, 235, 235, 236,
        235, 236],
       [186, 175, 180, 150, 156, 158, 144, 124, 132, 134, 148, 153, 150,
        146, 137, 134, 126, 109, 114, 235, 237, 234, 238, 236, 236, 236,
        236, 237],
       [145, 135, 137, 134, 122, 136, 112,  95,  94,  90,  93,  65,  60,
         66,  61,  66,  58,  66,  80, 164, 247, 235, 236, 237, 239, 237,
        237, 235],
       [140, 146, 136, 132, 129, 134, 100, 103, 100, 100,  87,  64,  66,
         65,  57,  57,  61,  61,  64,  65, 177, 242, 238, 238, 239, 238,
        238, 238],
       [141, 146, 140, 131, 130, 136,  93,  97, 102,  96,  78,  71,  68,
         64,  60,  61,  60,  55,  58,  48, 254, 238, 240, 239, 238, 237,
        237, 238],
       [146, 143, 137, 138, 129, 113,  94,  98, 101,  87,  75,  70,  68,
         63,  60,  58,  56,  57,  63,  81, 237, 237, 240, 240, 239, 240,
        240, 240]]
)

In [29]:
# Reshape the grayscale image tensor into a vector
gray_vector = reshape(gray_tensor, (784, 1))

# Reshape the color image tensor into a vector
# color_vector = reshape(color_tensor, (2352, 1))

In [30]:
def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = Variable(x0)
	with tf.GradientTape() as tape:
		tape.watch(x)
        # Define y using the multiply operation
		y = multiply(x, x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


In [31]:
model = constant(
    [[ 1.,  0., -1.]]
)

letter = constant(
    [[1., 0., 1.],
    [1., 1., 0.],
    [1., 0., 1.]]
)

# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())

1.0
